"""Public Pydantic models for all SDK domains."""

from .auth import (
    ApiKey,
    ApiKeyCreateResponse,
    LoginResponse,
    LoginUser,
    RefreshResponse,
)
from .backtesting import (
    AsyncBacktestStatus,
    AsyncBacktestSubmission,
    BacktestArchiveResult,
    BacktestRequest,
    BacktestResult,
    BacktestTradesResponse,
    Benchmark,
    BulkBacktestItemResult,
    BulkBacktestRequest,
    BulkBacktestResult,
)
from .config import (
    ExecutionConfigParam,
    ExecutionConfigSchema,
    TransactionCosts,
)
from .crypto_assets import (
    AssetMetadata,
    AssetTimestamps,
    CryptoAsset,
    Exchange,
    GlobalMarketResponse,
    MarketDataResponse,
    OHLCVResponse,
    RiskScores,
    TrendingResponse,
)
from .docs import (
    DocContentResponse,
    DocItem,
)
from .execution import (
    Account,
    CreateAccountRequest,
    EvaluateResult,
    Position,
    Trade,
)
from .kb import (
    KBBacklinksResponse,
    KBComputeResult,
    KBDocument,
    KBDocumentSections,
    KBDocumentSummary,
    KBGlossaryEntry,
    KBGlossaryResponse,
    KBIndicator,
    KBSearchResponse,
    KBSearchResult,
    KBSection,
    KBSignal,
    KBTag,
    KBTagDocuments,
)
from .market_data import (
    DirectionReading,
    MarketRegime,
    MarketSegment,
    RegimeReading,
    SegmentFeatures,
    VolatilityReading,
)
from .oracle import (
    DataQueryFilter,
    DataQueryRequest,
    DataQueryResponse,
    OracleAsyncBacktestStatus,
    OracleAsyncBacktestSubmission,
    OracleBacktestRequest,
    OracleBacktestResult,
    OracleBulkBacktestRequest,
    OracleBulkBacktestResult,
    OrderBy,
    RunInput,
    SievePrediction,
    SieveScoreRequest,
    SieveScoreResponse,
    SignalSpec,
    StrategyInput,
)
from .shared import SuccessResponse
from .signals import (
    EvaluateResponse,
    MatchResponse,
    MatchResult,
    SearchSignalsRequest,
    Signal,
    SignalBehaviorResult,
    SignalMetadata,
    ValidationResponse,
)
from .strategies import (
    CreateStrategyRequest,
    StrategyArchiveResult,
    StrategyDetail,
    StrategyListItem,
    StrategyVerification,
    UpdateStrategyRequest,
)
from .users import (
    TokenBreakdown,
    UserBacktest,
    UserMetrics,
    UserStrategy,
)

__all__ = [
    # Shared
    "SuccessResponse",
    # Auth
    "LoginUser",
    "LoginResponse",
    "RefreshResponse",
    "ApiKey",
    "ApiKeyCreateResponse",
    # Strategies
    "StrategyListItem",
    "StrategyDetail",
    "StrategyArchiveResult",
    "StrategyVerification",
    "CreateStrategyRequest",
    "UpdateStrategyRequest",
    # Config
    "ExecutionConfigSchema",
    "ExecutionConfigParam",
    "TransactionCosts",
    # Market data
    "MarketRegime",
    "RegimeReading",
    "DirectionReading",
    "VolatilityReading",
    "MarketSegment",
    "SegmentFeatures",
    # Backtesting
    "Benchmark",
    "BacktestRequest",
    "BulkBacktestRequest",
    "BacktestResult",
    "BulkBacktestItemResult",
    "BulkBacktestResult",
    "BacktestTradesResponse",
    "BacktestArchiveResult",
    "AsyncBacktestSubmission",
    "AsyncBacktestStatus",
    # Signals
    "Signal",
    "SignalMetadata",
    "SearchSignalsRequest",
    "MatchResult",
    "MatchResponse",
    "EvaluateResponse",
    "ValidationResponse",
    "SignalBehaviorResult",
    # Crypto Assets
    "CryptoAsset",
    "RiskScores",
    "AssetMetadata",
    "AssetTimestamps",
    "Exchange",
    "MarketDataResponse",
    "OHLCVResponse",
    "TrendingResponse",
    "GlobalMarketResponse",
    # Execution
    "CreateAccountRequest",
    "Account",
    "Position",
    "Trade",
    "EvaluateResult",
    # Docs
    "DocItem",
    "DocContentResponse",
    # KB
    "KBDocumentSummary",
    "KBDocument",
    "KBSection",
    "KBDocumentSections",
    "KBSearchResult",
    "KBSearchResponse",
    "KBTag",
    "KBTagDocuments",
    "KBGlossaryEntry",
    "KBGlossaryResponse",
    "KBBacklinksResponse",
    "KBSignal",
    "KBIndicator",
    "KBComputeResult",
    # Oracle
    "SignalSpec",
    "StrategyInput",
    "RunInput",
    "SieveScoreRequest",
    "SievePrediction",
    "SieveScoreResponse",
    "DataQueryFilter",
    "DataQueryRequest",
    "OrderBy",
    "DataQueryResponse",
    "OracleBacktestRequest",
    "OracleBulkBacktestRequest",
    "OracleBacktestResult",
    "OracleAsyncBacktestSubmission",
    "OracleAsyncBacktestStatus",
    "OracleBulkBacktestResult",
    # Users
    "UserMetrics",
    "TokenBreakdown",
    "UserStrategy",
    "UserBacktest",
]
